services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - nominatim

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev -- --host
    env_file:
      - ./frontend/.env.development  # Ensure this is explicitly loaded
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL  # <-- Ensure this references the loaded value
    stdin_open: true
    tty: true


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.3
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1g
    mem_limit: 4g

volumes:
  dev-db-data:
  dev-static-data:
  nominatim-data:
