# Generated by Django 5.1.4 on 2024-12-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badge_region_analyticsreport_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_logins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
