# Generated by Django 5.1.4 on 2024-12-25 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelisting',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
