# Generated by Django 5.1.4 on 2024-12-25 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pricelisting_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('date_imported', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
