# Generated by Django 5.1.4 on 2025-01-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pricelistimporthistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['product', 'store', 'date_added'], name='core_pricel_product_533b58_idx'),
        ),
    ]
