# Generated by Django 5.1.4 on 2025-01-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pricelisting_core_pricel_product_533b58_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='price_listing',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='product',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='store',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
            preserve_default=False,
        ),
    ]
