# Generated by Django 5.1.4 on 2025-01-16 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_shoppinglistitem_price_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
