# Generated by Django 5.1.4 on 2025-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_datasources_user_theme_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasources',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
