# Generated by Django 5.1.5 on 2025-02-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usersearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelisting',
            name='price_is_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasources'),
        ),
    ]
